name: nfcorpus
dataset: allenai/scirepeval
subset: nfcorpus
split_lookup:
  test: evaluation
standardize_splits: false
formatter:
  name: scirepeval
  args:
    fields_to_keep: ['title', 'abstract']
metadata:
  task: ranking
  domains:
    - clinical_medicine
  source_type: single_source
  input_context: structured
  output_context: ranking
  contributor: sergeyf
templates:
  0:
    answer_choices: null
    evaluate: true
    jinja: |
      You are RankLLM, an intelligent assistant that can rank passages based on their relevancy to the query.

      I will provide you with titles and abstracts of scientific papers, each indicated by a numerical identifier [].

      Rank the scientific papers based on their relevance to the search query. All the passages should be included and listed using identifiers, in descending order of relevance.
      The output format should be [a] > [b] when [a] is more relevant than [b] or [a] = [b] when [a] is equally relevant to [b], e.g., [4] > [2] > [1] = [3].

      For example, for the search query: "Does coffee make advil more effective?" and the following papers:
      {
        "id": "[1]",
        "title": "Sociological studies of the rich: a review",
        "abstract": "Three traits of the upper middle class are: drinking coffee, taking advil, and having vacations..."
      }
      {
        "id": "[2]",
        "title": "Caffeine and ibuprofen: a pharmacokinetic interaction study",
        "abstract": "The pharmacokinetic interaction between caffeine and ibuprofen was investigated in 12 healthy volunteers..."
      }
      {
        "id": "[3]",
        "title": "Studying the effect of caffeine on the pharmacokinetics of ibuprofen in late-stage cancer patients",
        "abstract": "The aim of this study was to investigate the effect of caffeine on the pharmacokinetics of ibuprofen in late-stage cancer patients..."
      }
      {
        "id": "[4]",
        "title": "My life",
        "abstract": "I woke up this morning with a headache. It was time to take some advil and drink some coffee. I felt better afterwards."
      }

      All four mention coffee and advil, but the second is about interactions, while the third is about interactions in a subpopulation that was not specified in the query. The first does not mention interactions. The correct ranking is therefore:

      [2] > [3] > [1] = [4]

      Now, rank the following passages based on their relevance to the search query: {{query}}.

      {{papers}}

      Search Query: {{query}}.

      Only respond with the ranking results, do not say any word or explain.

      |||

      {{ranking}}
    metadata:
      description_loc: before
